branches:
  except:
    - /^v\d+$/
language: ruby
rvm:
  - 2.3.0
cache: bundler
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.4"
  apt:
    packages:
      - libtag1-dev
before_script:
  - psql -c 'create database "rubyfm_test";' -U postgres
script: bundle exec rake test
