version: '2'

services:
  database:
    image: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    depends_on:
      - database
      - redis
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ''
      REDIS_URL: redis://redis:6379/0
      PORT: 3000
    ports:
      - "3000:3000"
    command: bundle exec rails server --port 3000 --binding 0.0.0.0
    volumes:
      - .:/app

  worker:
    build: .
    depends_on:
      - database
      - redis
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ''
      REDIS_URL: redis://redis:6379/0
      PORT: 3000
    command: bundle exec sidekiq -v
    volumes:
      - .:/app
