source 'https://rubygems.org'

gem 'activerecord', '>= 3.1', :require => 'active_record'
gem 'dropbox-sdk'
gem 'erubis', '~> 2.7.0'
gem 'minitest', :require => 'minitest/autorun', :group => 'test'
gem 'oj'
gem 'omniauth'
gem 'omniauth-dropbox-oauth2'
gem 'omniauth-twitter'
gem 'padrino', '0.12.4'
gem 'pg'
gem 'rack-test', :require => 'rack/test', :group => 'test'
gem 'rake'
gem 'sass'
gem 'thin'
