default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

local: &local
  <<: *default
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>


development:
  <<: *local
  database: rubyfm_development

test:
  <<: *local
  database: rubyfm_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
