default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development: &development
  <<: *default
  database: rubyfm
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>
test:
  <<: *development
  database: rubyfm_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
